package com.example.queue.seat_reservation.domain.user.entity;

import com.example.queue.seat_reservation.domain.wallet.entity.Wallet;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("User 엔티티 테스트")
class UserTest {

    private Validator validator;

    @BeforeEach
    void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    @DisplayName("User 엔티티 생성 성공")
    void createUser_Success() {
        // given
        String userId = "user123";
        String name = "홍길동";
        String email = "hong@example.com";

        // when
        User user = User.builder()
                .userId(userId)
                .name(name)
                .email(email)
                .build();

        // then
        assertThat(user).isNotNull();
        assertThat(user.getUserId()).isEqualTo(userId);
        assertThat(user.getName()).isEqualTo(name);
        assertThat(user.getEmail()).isEqualTo(email);
    }

    @Test
    @DisplayName("User와 Wallet 1:1 관계 확인")
    void userWalletRelationship() {
        // given
        User user = User.builder()
                .userId("user123")
                .name("홍길동")
                .email("hong@example.com")
                .build();

        Wallet wallet = Wallet.builder()
                .walletId(1L)
                .user(user)
                .cash(10000)
                .point(5000)
                .build();

        // when & then
        assertThat(user).isNotNull();
        assertThat(wallet.getUser()).isEqualTo(user);
    }

    @Test
    @DisplayName("User 이메일 필수값 검증")
    void validateEmail_Required() {
        // given
        User user = User.builder()
                .userId("user123")
                .name("홍길동")
                .email(null)
                .build();

        // when
        Set<ConstraintViolation<User>> violations = validator.validate(user);

        // then
        // JPA의 @Column(nullable = false)는 DB 레벨에서 검증되므로
        // Bean Validation을 추가하지 않은 경우 통과할 수 있음
        // 필요시 @NotNull 어노테이션 추가 권장
    }

    @Test
    @DisplayName("User 이메일 유니크 제약조건 테스트")
    void validateEmail_Unique() {
        // given
        String email = "hong@example.com";
        User user1 = User.builder()
                .userId("user1")
                .name("홍길동")
                .email(email)
                .build();

        User user2 = User.builder()
                .userId("user2")
                .name("김철수")
                .email(email)
                .build();

        // when & then
        // DB 레벨에서 unique 제약조건이 적용되므로
        // 실제로는 Repository 레이어 테스트에서 검증 필요
        assertThat(user1.getEmail()).isEqualTo(user2.getEmail());
    }

    @Test
    @DisplayName("User 생성 시 createdAt 자동 설정 확인")
    void createdAt_AutoGenerated() {
        // given
        User user = User.builder()
                .userId("user123")
                .name("홍길동")
                .email("hong@example.com")
                .build();

        // when & then
        // @CreatedDate는 JPA Auditing에 의해 자동 설정되므로
        // 실제로는 Repository 레이어 테스트에서 검증 필요
        assertThat(user).isNotNull();
    }

    @Test
    @DisplayName("User 빌더 패턴 테스트")
    void builderPattern() {
        // given & when
        User user = User.builder()
                .userId("user123")
                .name("홍길동")
                .email("hong@example.com")
                .build();

        // then
        assertThat(user.getUserId()).isEqualTo("user123");
        assertThat(user.getName()).isEqualTo("홍길동");
        assertThat(user.getEmail()).isEqualTo("hong@example.com");
    }

    @Test
    @DisplayName("User Getter 테스트")
    void getterTest() {
        // given
        String userId = "user123";
        String name = "홍길동";
        String email = "hong@example.com";
        LocalDateTime createdAt = LocalDateTime.now();

        User user = User.builder()
                .userId(userId)
                .name(name)
                .email(email)
                .build();

        // when & then
        assertThat(user.getUserId()).isEqualTo(userId);
        assertThat(user.getName()).isEqualTo(name);
        assertThat(user.getEmail()).isEqualTo(email);
    }
}
